level_data = {
    "name": "test",
    "width": 10,
    "height": 10,
    "money": 999,
    "days": [
        [100, 900, 2800],
        [200, 200, 300],
        [200, 900, 2800],
    ],
    "map": [
        { "type": "hill", "position": [0, 0] },
        { "type": "hill", "position": [1, 0] },
        { "type": "hill", "position": [2, 0] },
        { "type": "hill", "position": [3, 0] },
        { "type": "hill", "position": [4, 0] },
        { "type": "hill", "position": [5, 0] },
        { "type": "hill", "position": [6, 0] },
        { "type": "brokenground", "position": [0, 1] },
        { "type": "brokenground", "position": [1, 1] },
        { "type": "brokenground", "position": [2, 1] },
        { "type": "brokenground", "position": [3, 1] },
        { "type": "brokenground", "position": [4, 1] },
        { "type": "brokenground", "position": [5, 1] },
        { "type": "brokenground", "position": [6, 1] },
        { "type": "brokenground", "position": [7, 1] },
        { "type": "brokenground", "position": [8, 1] },
        { "type": "brokenground", "position": [9, 1] },
        { "type": "brokenground", "position": [0, 2] },
        { "type": "brokenground", "position": [1, 2] },
        { "type": "brokenground", "position": [2, 2] },
        { "type": "brokenground", "position": [3, 2] },
        { "type": "brokenground", "position": [4, 2] },
        { "type": "brokenground", "position": [5, 2] },
        { "type": "brokenground", "position": [6, 2] },
        { "type": "brokenground", "position": [7, 2] },
        { "type": "brokenground", "position": [8, 2] },
        { "type": "brokenground", "position": [9, 2] },
        { "type": "brokenground", "position": [0, 3] },
        { "type": "brokenground", "position": [1, 3] },
        { "type": "brokenground", "position": [2, 3] },
        { "type": "brokenground", "position": [3, 3] },
        { "type": "brokenground", "position": [4, 3] },
        { "type": "brokenground", "position": [5, 3] },
        { "type": "brokenground", "position": [6, 3] },
        { "type": "brokenground", "position": [7, 3] },
        { "type": "brokenground", "position": [8, 3] },
        { "type": "brokenground", "position": [9, 3] },
        { "type": "sea", "position": [0, 4] },
        { "type": "sea", "position": [1, 4] },
        { "type": "sea", "position": [2, 4] },
        { "type": "sea", "position": [3, 4] },
        { "type": "gold", "position": [9, 9] },
        { "type": "gold", "position": [8, 9] },
        { "type": "gold", "position": [7, 9] },
        { "type": "gold", "position": [6, 9] },
        { "type": "gold", "position": [5, 9] },
        { "type": "ground", "position": [1, 5] },
        { "type": "ground", "position": [2, 5] },
        { "type": "ground", "position": [3, 5] },
        { "type": "ground", "position": [4, 5] },
        { "type": "ground", "position": [5, 5] },
        { "type": "ground", "position": [6, 5] },
        { "type": "ground", "position": [7, 5] },
        { "type": "ground", "position": [8, 5] },
        { "type": "ground", "position": [9, 5] },
        { "type": "ground", "position": [10, 5] },
        { "type": "spawner", "position": [10, 1] },
        { "type": "spawner", "position": [10, 2] },
        { "type": "spawner", "position": [10, 3] },
    ],
    "tower": [
        { "type": "sunnytower", "position": [1, 2] }
    ]
}